---
- name: rebuild dankodeploy
  ansible.builtin.command:
    cmd: docker compose -f {{ dankodeploy_compose_file }} up -d --build
    chdir: "{{ dankodeploy_dir }}"
  become_user: "{{ dankodeploy_user }}"

- name: restart dankodeploy
  ansible.builtin.command:
    cmd: docker compose -f {{ dankodeploy_compose_file }} up -d
    chdir: "{{ dankodeploy_dir }}"
  become_user: "{{ dankodeploy_user }}"
